defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      permalink: /posts/:slug


background-positions:
- center
- left top
- left center
- left bottom
- right top
- right center
- right bottom
- center top
- center center
- center bottom

# plugin stuff
plugins:
  - jekyll-paginate-v2

_options:
  layout:
    hidden: true
  embed-video_html:
    embed: true
  content:
    styles: /editor.css
    embed: true
    left: left
    center: center
    right: right
    justify: full-width-text
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    table: true
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index.html'

############################################################

autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'archive in :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

# post loop's
page_blocks: []
_array_structures:
  page_blocks:
    - label: Blog Intro
      icon: edit
      value:
        _id: blog-intro
        background-image_path: /images/website_placeholder_5.jpg
        statement-paragraph: This is styled text to make a statement when you open your bog post to encourage people to read further, and make sure they know this is a written blog post
        regular-paragraph: continuing blog post to transition into main bog post body aksndl mlam p'ejw ofewno;f no;k mopqwkmp mq pw mowempoewkm   f'p  w mewop kneown onewon welkm ldkmwel  kj e rpkemw pekmfpw...

    - label: Podcast
      icon: mic
      value:
        _id: podcast
        podcast_image: /images/website-placeholder_3.jpg
        sub-heading: Podcast
        heading: Listen To This Episode On
        link-text-1: Apple
        link_url_1: https://apps.apple.com/us/app/apple-podcasts/id525463029
        link-text-2: Spotify
        link_url_2: https://open.spotify.com/genre/podcasts-page
        podcast-info: This is a short description

    - label: Video
      icon: live_tv
      value:
        _id: video
        embed-video_html: Add your embed code here.
